name: Build Checklists

on:
  push:
    branches:
      - main
      - C140-spins-and-things
  pull_request:
  workflow_dispatch: # This enables the manual trigger button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Compile checklists
        uses: alexnj/aviation-checklist-compiler-action@main
